Fix 'AttributeError: '_UnixSelectorEventLoop' object has no attribute 'call_soon'
See haata/pycapnp#1 for a discussion. The cause of this bug is still unknown to
me. But it likely has been fixed in Python 3.10. For some crazy reason, you can
just keep retrying the offending call, and the attribute will magically
'reappear'.