DynamicCapabilityClient: fix crash due to wrong types
In the last commit touching this line, a ')' was put in the wrong place, leading to errors like this one:

```
  File "capnp/lib/capnp.pyx", line 2172, in capnp.lib.capnp._DynamicCapabilityClient.__dir__
TypeError: unsupported operand type(s) for +: 'set' and 'tuple'
```